### ISSUE TITLE
Add Support for Unicode characters

### ISSUE THREAD

**Issue by john-henry** [barrelstrength/craft-sprout-base-reports#31]
We have clients who use reports for Commerce especially and customers names tent to have fadas/accents etc
It would also be handy for things like checkmarks

I added Unicode support here https://github.com/barrelstrength/craft-sprout-base-reports/pull/30 if you would consider it?

**Comment by BenParizek** [comment]
Thanks for the PR. Just released Sprout Reports v1.5.14 which includes this update.
